services:
  - type: web
    name: telegram-bot
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
