services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    region: oregon
    startCommand: "sh start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
